Match More functions
pret/pokeemerald pull request #1169
Opened 2020-09-02 20:04 UTC by PokeCodec

I merged the rest of my dozens of branches into one.

Better this than 6 or more PRs

2020-09-02 20:11 UTC, GriffinRichards commented
Doesn't match. Please test these locally

2020-09-02 20:29 UTC, PokeCodec commented
Alright, fixed!

2020-09-02 21:32 UTC, GriffinRichards requested changes

2020-09-02 21:32 UTC, GriffinRichards commented on include/constants/rgb.h
> +#define B(color) (((color) >> 10) & 0x1F)
These names imply to-RGB, but they're from-RGB. i.e. I'd expect `R(x) | G(y) | B(z)` to be equivalent to `RGB(x, y, z)`

2020-09-02 21:32 UTC, GriffinRichards commented on src/frontier_util.c
> +            } while (IsShinyOtIdPersonality(FRONTIER_BRAIN_OTID, j)); //See above comment
Second comment is unnecessary

2020-09-02 21:32 UTC, GriffinRichards commented on src/frontier_util.c
> +
Extra newline

2020-09-02 21:32 UTC, GriffinRichards commented on src/pokedex.c
> +		*(u16 *)(ptr + (y+1)*64 + (x+i)*2) = temp;
Tabs

2020-09-02 21:32 UTC, GriffinRichards commented on src/pokenav_main_menu.c
> +
More unnecessary whitespace

2020-09-02 21:32 UTC, GriffinRichards commented on src/pokenav_main_menu.c
> +
Unnecessary whitespace

2020-09-02 21:44 UTC, PokeCodec commented
Fixed!

2020-09-03 02:40 UTC, PokeCodec commented
I am 100% ready for this now!

2020-09-04 23:45 UTC, closed without merging