Match CheckBagHasSpace
pret/pokeemerald pull request #1179
Opened 2020-09-05 18:41 UTC by PokeCodec

This leaves one final function left to decompile and fix (with HandleAction_UseItem being the culprit).

2020-09-05 21:51 UTC, PokeCodec reviewed
The switch to ``if ((*(gBattleStruct->AI_itemFlags + gBattlerAttacker / 2) & 1)
            && (*(gBattleStruct->AI_itemFlags + gBattlerAttacker / 2) & 0x3E))`` SHOULD have caused a nonmatching, but it did not.

Thought this was too good of a quirk to not put in this PR.

2020-09-07 22:46 UTC, PokeCodec commented
I'm going to say this PR is ready for review.

2020-09-08 17:53 UTC, PikalaxALT requested changes

2020-09-08 17:53 UTC, PikalaxALT commented on src/m4a_1.s
> +	ldr r0, [r0] @ Set the SoundInfo pointer to sound area
Comment incorrect

2020-09-08 20:26 UTC, PokeCodec commented
Fixed

2020-09-08 20:31 UTC, PikalaxALT approved these changes

2020-09-08 20:31 UTC, merged