Match BattleIntroOpponent1SendsOutMonAnimation
pret/pokeemerald pull request #1180
Opened 2020-09-08 21:14 UTC by PokeCodec

Thanks everyone! With this, all the naked functions are done! We only have fakematches left.

However, the includes are going to have to be cleaned up, but otherwise, this is a monumental milestone!

2020-09-08 23:36 UTC, PikalaxALT requested changes

2020-09-08 23:36 UTC, PikalaxALT commented on berry_fix/Makefile
> +override CFLAGS += -mthumb-interwork -Wimplicit -Wparentheses -Werror -O2 -fhex-asm -nostdlib
Revert

2020-09-08 23:36 UTC, PikalaxALT commented on berry_fix/payload/Makefile
> +override CC1FLAGS += -mthumb-interwork -Wimplicit -Wparentheses -Werror -O2 -fhex-asm -nostdlib
Revert

2020-09-08 23:36 UTC, PikalaxALT commented on berry_fix/Makefile
> +ASFLAGS := -mcpu=arm7tdmi -mthumb-interwork
Revert

2020-09-08 23:36 UTC, PikalaxALT commented on berry_fix/payload/Makefile
> +ASFLAGS := -mcpu=arm7tdmi -mthumb-interwork
Revert

2020-09-08 23:36 UTC, PikalaxALT commented on libagbsyscall/Makefile
> +ASFLAGS := -mcpu=arm7tdmi -mthumb-interwork
Revert

2020-09-08 23:55 UTC, PokeCodec commented
Done!

2020-09-08 23:57 UTC, PikalaxALT approved these changes

2020-09-09 00:01 UTC, merged

2020-09-09 00:01 UTC, PikalaxALT commented
Ladies and gentlemen, the Wicked Witch of the HandleAction_UseItem is dead