Match PrintMonWeight
pret/pokeemerald pull request #1183
Opened 2020-09-09 20:37 UTC by PokeCodec

Credit goes to @Kaz for this one. I also added an enum for height and weight

2020-09-09 21:04 UTC, PokeCodec commented
I hate this code

2020-09-10 17:36 UTC, PikalaxALT requested changes

2020-09-10 17:36 UTC, PikalaxALT commented on src/battle_script_commands.c
> +    s32 i, lastMonId;
Revert or finish matching

2020-09-10 17:36 UTC, PikalaxALT commented on src/berry_crush.c
> +	color |= params[7];
Fix indentation

2020-09-10 17:36 UTC, PikalaxALT commented on src/dewford_trend.c
> +#ifndef NONMATCHING
No.

2020-09-10 22:07 UTC, PokeCodec commented
Done

2020-09-10 23:36 UTC, PikalaxALT approved these changes

2020-09-10 23:36 UTC, merged