Document some bugs
pret/pokeemerald pull request #1186
Opened 2020-09-12 16:58 UTC by kiliwily

2020-09-12 17:35 UTC, ShinyDragonHunter commented
When updating bugs_and_glitches.md, it’s worth explaining what the bug is and why it happens. This is akin to how it’s done in pokecrystal’s documentation on bugs and glitches.

2020-09-12 17:58 UTC, kiliwily commented
The bug is already documented in bugs_and_glitches.md akin it is done in pokecrystal. I just added an alternative way to fix it.

2020-09-19 15:15 UTC, GriffinRichards requested changes
These are probably fine for now, but I'd prefer if these simple fixes were in directives rather than described. For example `//To fix this add another if statement after the instruction that sets currentHP = 1 if currentHP <= 0.` is unnecessarily wordy

2020-09-19 15:15 UTC, GriffinRichards commented on src/metatile_behavior.c
> +    //change the metatile behavior of the narrower water door with porymaps tilset editor.
typo, `tilset`. Also space between `||` and `metatileBehavior`

2020-09-19 15:15 UTC, GriffinRichards commented on src/battle_util.c
> +        //BUG: The safariEscapeFactor is unintetionally able to become 0 (but it can not become negative!). This causes the pokeblock throw glitch.
Put a space after `//`

2020-09-19 15:31 UTC, ShinyDragonHunter commented
In one of the changes, you wrote `safariEscapeFactor is unintetionally`

2020-09-19 18:55 UTC, kiliwily commented
Typos are fixed. Spaces are added after //. Pomeg fix is shortend.
Should I write the fixes as commented out code?

2020-09-19 20:06 UTC, PokeCodec commented
> Typos are fixed. Spaces are added after //. Pomeg fix is shortend.
> Should I write the fixes as commented out code?

Yes

2020-09-19 22:09 UTC, GriffinRichards commented
That's not necessary, at that point they should just be directives. Comments are fine for now

2020-09-19 22:09 UTC, GriffinRichards approved these changes

2020-09-19 22:09 UTC, merged