fakematch fixes, begin documenting Berry Crush (based on #1187)
pret/pokeemerald pull request #1265
Opened 2020-12-11 05:28 UTC by Kurausukun

## Description
Credit to Kaz (kazblox) for the PR this was based on, I just merged it with master and fixed conflicts.

## **Discord contact info**
Kurausukun#9923

2020-12-12 02:57 UTC, GriffinRichards requested changes

2020-12-12 02:57 UTC, GriffinRichards commented on src/menu_specialized.c
>          if ((species == SPECIES_NIDORAN_F || species == SPECIES_NIDORAN_M) && !StringCompare(dst, gSpeciesNames[species]))
Fix indentation

2020-12-12 02:57 UTC, GriffinRichards commented on src/overworld.c
> +#define linkGender(obj) obj->singleMovementActive
Why is something called `linkGender` being used to access a field called `singleMovementActive`?

2020-12-12 02:57 UTC, GriffinRichards commented on src/overworld.c
> +    linkDirection(objEvent) = 2;
Is this a direction or a range? If it's a direction it should use the `DIR` constants

2020-12-12 02:57 UTC, GriffinRichards commented on src/overworld.c
> +        linkDirection(objEvent) = a2;
Let's name `a2` while we're here

2020-12-12 03:01 UTC, kazblox commented
GriffinRichards: **The game reuses the direction and range variables as gender and direction variables when in Link Mode.** Hence the names linkGender and linkDirection.

2020-12-12 03:10 UTC, GriffinRichards commented
Does it not match with a union? If not please put a comment at the define that the field is being re-used, it's confusing at a glance

2020-12-12 03:22 UTC, kazblox commented
It could, but it would create useless cruft just to make space for two miniscule members, especially when they're far away from each other, which means I would have to create two unions of "link1" and "link2." It's better to just leave them as defines, maybe I should move them to the event object header itself so that people don't get lost.

Or should I introduce the unions anyway? How would this benefit?

2020-12-12 03:27 UTC, GriffinRichards commented
Just a comment stating that they're being re-used is fine then

2020-12-15 04:22 UTC, GriffinRichards approved these changes

2020-12-15 04:22 UTC, merged